In [76]:
import pandas as pd

In [77]:
box_hill_csv = pd.read_csv("../P2 dataset/kim/Box Hill.csv")
carlton_csv = pd.read_csv("../P2 dataset/kim/Carlton.csv")
colling_csv = pd.read_csv("../P2 dataset/kim/Collingwood.csv")
dock_csv = pd.read_csv("../P2 dataset/kim/Docklands.csv")
east_mel_csv = pd.read_csv("../P2 dataset/kim/East Melbourne.csv")
fle_csv = pd.read_csv("../P2 dataset/kim/Flemington.csv")
haw_csv = pd.read_csv("../P2 dataset/kim/Hawthorn.csv")
ken_csv = pd.read_csv("../P2 dataset/kim/Kensington.csv")
mel_csv = pd.read_csv("../P2 dataset/kim/Melbourne.csv")
north_mel_csv = pd.read_csv("../P2 dataset/kim/North Melbourne.csv")
park_csv = pd.read_csv("../P2 dataset/kim/Parkville.csv")
port_mel_csv = pd.read_csv("../P2 dataset/kim/Port Melbourne.csv")
rich_csv = pd.read_csv("../P2 dataset/kim/Richmond.csv")
south_mel_csv = pd.read_csv("../P2 dataset/kim/South Melbourne.csv")
south_yarra_csv = pd.read_csv("../P2 dataset/kim/South Yarra.csv .csv")
sbank_csv = pd.read_csv("../P2 dataset/kim/Southbank.csv")
stkida_csv = pd.read_csv("../P2 dataset/kim/St Kilda.csv")
west_mel_csv = pd.read_csv("../P2 dataset/kim/West Melbourne.csv")

In [78]:
box_hill = pd.DataFrame(box_hill_csv)
car = pd.DataFrame(carlton_csv)
colling = pd.DataFrame(colling_csv)
dock = pd.DataFrame(dock_csv)
eastmel = pd.DataFrame(east_mel_csv)
fle = pd.DataFrame(fle_csv)
haw = pd.DataFrame(haw_csv)
ken = pd.DataFrame(ken_csv)
mel = pd.DataFrame(mel_csv)
nmel = pd.DataFrame(north_mel_csv)
park = pd.DataFrame(park_csv)
portmel = pd.DataFrame(port_mel_csv)
rich = pd.DataFrame(rich_csv)
smel = pd.DataFrame(south_mel_csv)
syarra = pd.DataFrame(south_yarra_csv)
sbank = pd.DataFrame(sbank_csv)
stkilda = pd.DataFrame(stkida_csv)
wmel = pd.DataFrame(west_mel_csv)

In [79]:
box_hill.head()
box_hill.columns
box_hill.shape

(642, 9)

In [80]:
box_hill=box_hill[['Description','2018','2019','2020']]
car=car[['Description','2018','2019','2020']]
colling=colling[['Description','2018','2019','2020']]
dock=dock[['Description','2018','2019','2020']]
eastmel=eastmel[['Description','2018','2019','2020']]
fle=fle[['Description','2018','2019','2020']]
haw=haw[['Description','2018','2019','2020']]
ken=ken[['Description','2018','2019','2020']]
mel=mel[['Description','2018','2019','2020']]
nmel=nmel[['Description','2018','2019','2020']]
park=park[['Description','2018','2019','2020']]
portmel=portmel[['Description','2018','2019','2020']]
rich=rich[['Description','2018','2019','2020']]
smel=smel[['Description','2018','2019','2020']]
syarra=syarra[['Description','2018','2019','2020']]
sbank=sbank[['Description','2018','2019','2020']]
stkilda=stkilda[['Description','2018','2019','2020']]
wmel=wmel[['Description','2018','2019','2020']]

In [81]:
box_hill = box_hill.iloc[[0,1,2,3,8,211,212,215,219,220,252,255,256,266]]

In [82]:
box_hill = box_hill.rename(columns={'2020':'2020_BoxHill'})
box_hill.reset_index(drop=True, inplace=True)

In [83]:
car = car.rename(columns={'2020':'2020_Carlton'})
colling = colling.rename(columns={'2020':'2020_Collingwood'})
dock = dock.rename(columns={'2020':'2020_Dockland'})
eastmel = eastmel.rename(columns={'2020':'2020_E_Mel'})
fle = fle.rename(columns={'2020':'2020_Flemington'})
haw = haw.rename(columns={'2020':'2020_Hawthorn'})
ken = ken.rename(columns={'2020':'2020_Kensington'})
mel = mel.rename(columns={'2020':'2020_Mel'})
nmel = nmel.rename(columns={'2020':'2020_N_Mel'})
park = park.rename(columns={'2020':'2020_Parkville'})
portmel = portmel.rename(columns={'2020':'2020_Port_Mel'})
rich = rich.rename(columns={'2020':'2020_Richmond'})
smel = smel.rename(columns={'2020':'2020_S_Mel'})
syarra = syarra.rename(columns={'2020':'2020_S_Yarra'})
sbank = sbank.rename(columns={'2020':'2020_S_Bank'})
stkilda = stkilda.rename(columns={'2020':'2020_StKilda'})
wmel = wmel.rename(columns={'2020':'2020_W_Mel'})

In [84]:
box_hill.head

<bound method NDFrame.head of                                       Description       2018       2019  \
0             Estimated resident population (no.)    22627.0    23331.0
1                Population density (persons/km2)     3226.9     3327.3
2     Estimated resident population - males (no.)    11108.0    11577.0
3   Estimated resident population - females (no.)    11519.0    11754.0
4   Working age population (aged 15-64 years) (%)       73.7       74.5
5           Accommodation and food services (no.)      184.0      196.0
6         Transport, postal and warehousing (no.)      136.0      162.0
7   Rental, hiring and real estate services (no.)      403.0      447.0
8                    Education and training (no.)       52.0       58.0
9         Health care and social assistance (no.)      218.0      232.0
10             Value of residential building ($m)      118.0      150.0
11             Houses - number of transfers (no.)      157.0      122.0
12                 Houses - median sale price ($)  1450000.0  1240000.0
13                                    Buses (no.)       68.0       80.0

    2020_BoxHill
0        23981.0
1         3420.0
2        11909.0
3        12072.0
4           74.0
5          216.0
6          172.0
7          458.0
8           67.0
9          261.0
10         307.0
11         135.0
12     1409000.0
13          79.0  >

In [85]:
result = pd.merge(box_hill, car,how='left', on=['Description'])
result = pd.merge(result, colling,how='left', on=['Description'])
result = pd.merge(result, dock,how='left', on=['Description'])
result = pd.merge(result, eastmel,how='left', on=['Description'])
result = pd.merge(result, fle,how='left', on=['Description'])
result = pd.merge(result, haw,how='left', on=['Description'])
result = pd.merge(result, ken,how='left', on=['Description'])
result = pd.merge(result, mel,how='left', on=['Description'])
result = pd.merge(result, nmel,how='left', on=['Description'])
result = pd.merge(result, park,how='left', on=['Description'])
result = pd.merge(result, portmel,how='left', on=['Description'])
result = pd.merge(result, rich,how='left', on=['Description'])
result = pd.merge(result, smel,how='left', on=['Description'])
result = pd.merge(result, syarra,how='left', on=['Description'])
result = pd.merge(result, sbank,how='left', on=['Description'])
result = pd.merge(result, stkilda,how='left', on=['Description'])
result = pd.merge(result, wmel,how='left', on=['Description'])

/var/folders/mz/ytcv9vg56yqf64xqlxptmkbc0000gn/T/ipykernel_13661/3737355814.py:3: FutureWarning: Passing 'suffixes' which cause duplicate columns {'2019_x', '2018_x'} in the result is deprecated and will raise a MergeError in a future version.
  result = pd.merge(result, dock,how='left', on=['Description'])
/var/folders/mz/ytcv9vg56yqf64xqlxptmkbc0000gn/T/ipykernel_13661/3737355814.py:5: FutureWarning: Passing 'suffixes' which cause duplicate columns {'2019_x', '2018_x'} in the result is deprecated and will raise a MergeError in a future version.
  result = pd.merge(result, fle,how='left', on=['Description'])
/var/folders/mz/ytcv9vg56yqf64xqlxptmkbc0000gn/T/ipykernel_13661/3737355814.py:7: FutureWarning: Passing 'suffixes' which cause duplicate columns {'2019_x', '2018_x'} in the result is deprecated and will raise a MergeError in a future version.
  result = pd.merge(result, ken,how='left', on=['Description'])
/var/folders/mz/ytcv9vg56yqf64xqlxptmkbc0000gn/T/ipykernel_13661/3737355814.py:9: FutureWarning: Passing 'suffixes' which cause duplicate columns {'2019_x', '2018_x'} in the result is deprecated and will raise a MergeError in a future version.
  result = pd.merge(result, nmel,how='left', on=['Description'])
/var/folders/mz/ytcv9vg56yqf64xqlxptmkbc0000gn/T/ipykernel_13661/3737355814.py:11: FutureWarning: Passing 'suffixes' which cause duplicate columns {'2019_x', '2018_x'} in the result is deprecated and will raise a MergeError in a future version.
  result = pd.merge(result, portmel,how='left', on=['Description'])
/var/folders/mz/ytcv9vg56yqf64xqlxptmkbc0000gn/T/ipykernel_13661/3737355814.py:13: FutureWarning: Passing 'suffixes' which cause duplicate columns {'2019_x', '2018_x'} in the result is deprecated and will raise a MergeError in a future version.
  result = pd.merge(result, smel,how='left', on=['Description'])
/var/folders/mz/ytcv9vg56yqf64xqlxptmkbc0000gn/T/ipykernel_13661/3737355814.py:15: FutureWarning: Passing 'suffixes' which cause duplicate columns {'2019_x', '2018_x'} in the result is deprecated and will raise a MergeError in a future version.
  result = pd.merge(result, sbank,how='left', on=['Description'])
/var/folders/mz/ytcv9vg56yqf64xqlxptmkbc0000gn/T/ipykernel_13661/3737355814.py:17: FutureWarning: Passing 'suffixes' which cause duplicate columns {'2019_x', '2018_x'} in the result is deprecated and will raise a MergeError in a future version.
  result = pd.merge(result, wmel,how='left', on=['Description'])

In [86]:
result.head(14)

,Description,2018_x,2019_x,2020_BoxHill,2018_y,2019_y,2020_Carlton,2018_x,2019_x,2020_Collingwood,...,2020_S_Yarra,2018_y,2019_y,2020_S_Bank,2018_x,2019_x,2020_StKilda,2018_y,2019_y,2020_W_Mel
0,Estimated resident population (no.),22627.0,23331.0,23981.0,23261.0,24709.0,25670.0,10377.0,10990.0,11529.0,...,6904.0,24424.0,26321.0,27444.0,29886.0,30453.0,30772.0,3.0,3.0,3.0
1,Population density (persons/km2),3226.9,3327.3,3420.0,12791.3,13587.6,14116.0,8189.6,8673.3,9098.7,...,4594.4,7944.6,8561.6,8926.9,7661.1,7806.5,7888.2,0.5,0.5,0.5
2,Estimated resident population - males (no.),11108.0,11577.0,11909.0,10875.0,11644.0,12144.0,5216.0,5548.0,5832.0,...,3255.0,12389.0,13342.0,13922.0,15165.0,15475.0,15651.0,2.0,2.0,2.0
3,Estimated resident population - females (no.),11519.0,11754.0,12072.0,12386.0,13065.0,13526.0,5161.0,5442.0,5697.0,...,3649.0,12035.0,12979.0,13522.0,14721.0,14978.0,15121.0,1.0,1.0,1.0
4,Working age population (aged 15-64 years) (%),73.7,74.5,74.0,89.5,90.3,90.6,81.5,82.0,81.9,...,74.0,88.6,87.3,86.0,82.2,82.2,81.6,100.0,100.0,100.0
5,Accommodation and food services (no.),184.0,196.0,216.0,198.0,193.0,208.0,117.0,111.0,113.0,...,66.0,148.0,163.0,165.0,228.0,224.0,227.0,3.0,5.0,6.0
6,"Transport, postal and warehousing (no.)",136.0,162.0,172.0,125.0,138.0,159.0,83.0,95.0,109.0,...,23.0,108.0,114.0,117.0,154.0,180.0,163.0,14.0,10.0,11.0
7,"Rental, hiring and real estate services (no.)",403.0,447.0,458.0,408.0,397.0,410.0,276.0,281.0,275.0,...,302.0,434.0,469.0,525.0,777.0,781.0,742.0,38.0,45.0,44.0
8,Education and training (no.),52.0,58.0,67.0,35.0,44.0,47.0,34.0,40.0,40.0,...,19.0,42.0,45.0,48.0,78.0,83.0,88.0,NaN,NaN,NaN
9,Health care and social assistance (no.),218.0,232.0,261.0,214.0,225.0,234.0,71.0,69.0,86.0,...,192.0,161.0,160.0,151.0,201.0,214.0,216.0,NaN,NaN,NaN
10,Value of residential building ($m),118.0,150.0,307.0,39.0,29.0,40.0,119.0,9.0,161.0,...,47.0,683.0,279.0,515.0,206.0,43.0,305.0,NaN,NaN,NaN
11,Houses - number of transfers (no.),157.0,122.0,135.0,36.0,41.0,37.0,40.0,33.0,31.0,...,13.0,NaN,NaN,NaN,73.0,80.0,56.0,NaN,NaN,NaN
12,Houses - median sale price ($),1450000.0,1240000.0,1409000.0,1410000.0,1457500.0,1395000.0,1125999.5,1035000.0,1100000.0,...,3722500.0,NaN,NaN,NaN,1705000.0,1600000.0,2130000.0,NaN,NaN,NaN
13,Buses (no.),68.0,80.0,79.0,27.0,29.0,22.0,12.0,15.0,12.0,...,29.0,124.0,114.0,101.0,54.0,54.0,64.0,NaN,NaN,NaN

In [87]:
result.to_csv("../P2 dataset/clean dataset/region_summary.csv")